#!/usr/bin/env python3
# GUI to manage movement and action queues
# Copyright (C) 2022 David P. Rideout
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
import tkinter as tk
from tkinter import ttk
# import time

class qgui(tk.Tk):
  def __init__(s, act):
    super().__init__()
    s.act = act
    s.title('Queue')
    s.columnconfigure(0)
    s.columnconfigure(1)
#     s.update()
#     s.bind('<1>', s.update)
    s.n = 0

  def update(s):
    fp = open('.queue', 'r')
    r = 0
    for l in fp:
      #if l[0]=='#': continue
#       ls = l.split()
#       if ls[col]=='-': continue
#       self.nums.append(float(ls[col]))
#       ttk.Label(s, text=l[:-1], borderwidth=0, background='pink', anchor=tk.CENTER).grid(column=0, row=r, sticky=tk.EW, ipadx=3, ipady=0)
      ttk.Label(s, text=l[:-1]).grid(column=0, row=r, sticky=tk.EW, ipadx=4)
      ttk.Button(s, text=s.act).grid(column=1, row=r)
      r += 1
    if r>s.n: s.n=r
    else:
      while r<s.n:
        ttk.Label(s, text='', sticky=tk.EW).grid(column=0, row=r, ipadx=4)
        ttk.Label(s, text='', sticky=tk.EW).grid(column=1, row=r)
        r += 1
    fp.close()
    print('r =', r, 'n =', s.n)

#   def refresh(s):
#     s.after(

qg = qgui('Move')

# for i in range(10):
#   time.sleep(1)
#   print(i)
#   qg.event_generate('<1>')
i=0
def fn():
  global i
  print(i)
  qg.update()
  i += 1
  qg.after(3000, fn)

fn()
  
qg.mainloop()

# deleted figures are not removed properly.  Fix or just leave them? (27apr022)

